# Generated by Django 5.1.7 on 2025-03-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numDocumento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
