# Generated by Django 5.1.7 on 2025-03-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numDocumento',
            field=models.CharField(max_length=10),
        ),
    ]
