# Generated by Django 5.1.7 on 2025-03-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_numdocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numDocumento',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
