# Generated by Django 5.1.7 on 2025-03-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(choices=[('E', 'credito'), ('T', 'debito')], max_length=1)),
                ('numeroTarjeta', models.CharField(max_length=16)),
                ('numeroSeguridad', models.CharField(max_length=3)),
                ('fechaVencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
