# Generated by Django 5.1.6 on 2025-03-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idBebida", models.CharField(max_length=30)),
                ("descripcion", models.TextField()),
                ("precio", models.FloatField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[("Geseosa", "Geseosa"), ("Agua", "Agua")],
                        max_length=20,
                    ),
                ),
                (
                    "cantidad",
                    models.CharField(
                        choices=[("237 ml", "237 ml"), ("280 ml", "280 ml")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idPlato", models.CharField(max_length=30)),
                ("descripcion", models.TextField()),
                ("precio", models.FloatField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[("Combo", "Combo"), ("Plato Fuerte", "Plato Fuerte")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
