# Generated by Django 5.1.6 on 2025-03-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bebida",
            name="categoria",
            field=models.CharField(
                choices=[("Gaseosa", "Gaseosa"), ("Agua", "Agua")], max_length=20
            ),
        ),
    ]
