# Generated by Django 5.1.6 on 2025-03-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_bebida_categoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bebida",
            name="id",
        ),
        migrations.RemoveField(
            model_name="plato",
            name="id",
        ),
        migrations.AddField(
            model_name="bebida",
            name="nombre",
            field=models.CharField(default="sin nombre", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plato",
            name="nombre",
            field=models.CharField(default="lol", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bebida",
            name="idBebida",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="plato",
            name="idPlato",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
